trigger:
  - master
  - dev

pool:
  vmImage: 'ubuntu-16.04'
strategy:
  matrix:
    Python37:
      PYTHON_VERSION: '3.7'
    Python38:
      PYTHON_VERSION: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
  displayName: 'Use Python $(PYTHON_VERSION)'

- script: |
    python -m pip install --upgrade pip
    pip install .[testing]
  displayName: 'Install package'

- script: |
    pytest -v liso
  displayName: 'pytest'
