name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Ubuntu:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
        h5py: [3]
        include:
          - python: 3.7
            h5py: 2

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[test]

    - name: Install additional dependencies
      run: python -m pip install h5py==2.10
      if: matrix.h5py == '2'

    - name: Lint with pylint
      run: |
        pylint liso/experiment liso/scan liso/io liso/simulation liso/proc liso/visualization

    - name: Test with pytest
      run: |
        pytest -v ./liso
